export const BRAND_CONFIG = {
  name: 'LeadLinked',
  productName: 'LeadLinked-CTQ',
  tagline: 'Client Truth Questionnaire',
  systemDescription: 'Proprietary Strategic Business Intelligence Diagnostic',
  agencyDescriptor: 'Strategic Creative & Growth Agency',
  logoUrl: '/leadlinked-logo.png',
  fonts: {
    heading: 'Bricolage Grotesque, sans-serif',
    body: 'Inter, sans-serif',
    mono: 'Geist Mono, SF Mono, Menlo, monospace',
  },
  colors: {
    background: '#FBFBFA',
    surface: '#FFFFFF',
    surfaceSubtle: '#F7F6F3',
    border: '#EAEAEA',
    borderSubtle: 'rgba(0, 0, 0, 0.06)',
    textPrimary: '#111111',
    textSecondary: '#666663',
    textMuted: '#94938F',
    accentPastelBlue: '#E1F3FE',
    accentPastelBlueText: '#1F6C9F',
    accentPastelGreen: '#EDF3EC',
    accentPastelGreenText: '#346538',
    accentPastelYellow: '#FBF3DB',
    accentPastelYellowText: '#956400',
    accentPastelRed: '#FDEBEC',
    accentPastelRedText: '#9F2F2D',
  },
  limits: {
    maxSingleFileSizeMB: 8, // Max single file upload direct
    maxTotalFilesPerQuestion: 5,
    acceptedMimeTypes: [
      'image/jpeg',
      'image/png',
      'image/webp',
      'image/svg+xml',
      'application/pdf',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.ms-powerpoint',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      'text/plain',
      'text/csv',
    ],
  },
};
